[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
lottery_platform = "AA7crqzoJE15cTM8aQGrPP7FLHsCc8i2YcFkQNNwhShA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
